networks:
  custom_network:
    driver: bridge
    name: custom_network

volumes:
  postgres_data_full_app_office:
    name: postgres_data_full_app_office
  pgadmin_data_full_app_office:
    name: pgadmin_data_full_app_office
  rabbitmq_data_full_app_office:
    name: rabbitmq_data_full_app_office

services:
  postgres_app:
    image: postgres:latest
    container_name: postgres_container
    restart: no
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data_full_app_office:/var/lib/postgresql/data
    networks:
      - custom_network
    ports:
      - "5432:5432"

  pgadmin_app:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data_full_app_office:/var/lib/pgadmin
    networks:
      - custom_network
    ports:
      - "5050:80"
    depends_on:
      - postgres_app

  python_app:
    container_name: python_container
    restart: no
    build:
      context: ./python_app
      dockerfile: Dockerfile
    volumes:
      - ./python_app:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - custom_network
    depends_on:
      - rabbitmq_app

  rabbitmq_app:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq_container
    restart: no
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
    volumes:
      - rabbitmq_data_full_app_office:/var/lib/rabbitmq
    networks:
      - custom_network
    depends_on:
      - postgres_app

  express_app:
    container_name: express_app_container
    restart: no
    build:
      context: ./express_app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./express_app:/app
      - /app/node_modules
    networks:
      - custom_network
    depends_on:
      - postgres_app
