# Use the official Python image
FROM python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt 

# Start the app (for debugging purposes)
CMD ["tail", "-f", "/dev/null"]
