# Use the official Python image
FROM python-add-01-dep:latest

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application files
COPY . .

# Start the app (for debugging purposes)
CMD ["python3","trail.py"]
