apiVersion: v1
kind: Service
metadata:
  name: pyapp-sub-service
spec:
  type: NodePort
  selector:
    app: pyapp-sub
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30089
---
apiVersion: v1  # ✅ Use v1 for Pods
kind: Pod
metadata:
  name: pyapp-sub
  labels:
    app: pyapp-sub
spec:
  containers:
    - name: pyapp-sub
      image: py-jup-rabbitmq:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8888
      volumeMounts:
        - mountPath: "/app"
          name: workspace-volume
  volumes:
    - name: workspace-volume
      hostPath:
        path: "/home/ajay/kubeapp/pyapp"
        type: Directory

