apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:4.0.7-management
      ports:
        - containerPort: 5672 # RabbitMQ Server Port
        - containerPort: 15672 # Management UI Port
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq_user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbitmq_password"
        - name: RABBITMQ_HOST # ✅ Use correct service name
          value: "rabbitmq-service"
      resources:
        requests:
          memory: "512Mi" # Request 512 MB of memory
          cpu: "250m" # Request 0.25 CPU
        limits:
          memory: "1Gi" # Limit to 1 GB of memory
          cpu: "500m" # Limit to 0.5 CPU

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672 # Optional: Expose the server port (for messaging)

    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31567 # Expose management UI on this NodePort
